from __future__ import annotations

import argparse
import datetime as dt
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

from precommit_log_paths import HookReportPaths, build_report_paths, write_report_to_paths


HOOK_ID = "forbid-unity-debug-log"
SCRIPT_PATH = "scripts/precommit/forbid_debug_log.py"

PROJECT_ROOTS = (
    "Assets/_Project/Code/",
    "Assets/_Project/Tests/",
)

BANNED_PATTERNS = (
    "UnityEngine.Debug.Log(",
    "UnityEngine.Debug.LogWarning(",
    "UnityEngine.Debug.LogError(",
    "Debug.Log(",
    "Debug.LogWarning(",
    "Debug.LogError(",
)

ALLOWED_DEBUG_SYMBOLS = {
    "GR_DEBUG",
    "GR_COMBAT_DEBUG",
    "GR_M0_PROTOTYPE",
    "GR_DEBUG_OVERLAY",
    "GR_MEMORY_DEBUG",
    "NHEM_DI_DEBUG",
}

ALLOWED_PATH_KEYWORDS = (
    "NhemLogger",
    "NhemLogging",
    "/Logging/",
    "/Logger/",
)

PREPROCESSOR_IF_RE = re.compile(r"^\s*#\s*(if|elif)\s+(.+?)\s*$")
PREPROCESSOR_ENDIF_RE = re.compile(r"^\s*#\s*endif\b")
PREPROCESSOR_ELSE_RE = re.compile(r"^\s*#\s*else\b")


@dataclass(frozen=True)
class Failure:
    path: Path
    line: int
    pattern: str
    source_line: str


def run_git(args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        shell=False,
    )


def normalize_path(path: Path | str) -> str:
    return str(path).replace("\\", "/")


def is_project_cs_file(path: Path) -> bool:
    normalized = normalize_path(path)
    return path.suffix == ".cs" and any(normalized.startswith(root) for root in PROJECT_ROOTS)


def is_allowed_path(path: Path) -> bool:
    normalized = normalize_path(path)
    return any(keyword in normalized for keyword in ALLOWED_PATH_KEYWORDS)


def collect_all_project_cs_files() -> list[Path]:
    result = run_git(["ls-files", "Assets/_Project"])

    if result.returncode != 0:
        print("[FAIL] Could not collect project C# files via git ls-files.")
        print(result.stderr)
        raise SystemExit(1)

    files: list[Path] = []

    for line in result.stdout.splitlines():
        path = Path(line.strip())
        if is_project_cs_file(path):
            files.append(path)

    return sorted(files, key=lambda p: normalize_path(p).lower())


def collect_staged_project_cs_files() -> list[Path]:
    result = run_git(["diff", "--cached", "--name-only", "--diff-filter=ACMR"])

    if result.returncode != 0:
        print("[FAIL] Could not collect staged files.")
        print(result.stderr)
        raise SystemExit(1)

    files: list[Path] = []

    for line in result.stdout.splitlines():
        path = Path(line.strip())
        if is_project_cs_file(path):
            files.append(path)

    return sorted(files, key=lambda p: normalize_path(p).lower())


def expression_mentions_allowed_symbol(expression: str) -> bool:
    tokens = set(re.findall(r"[A-Za-z_][A-Za-z0-9_]*", expression))
    return bool(tokens & ALLOWED_DEBUG_SYMBOLS)


def line_has_banned_log(line: str) -> str | None:
    for pattern in BANNED_PATTERNS:
        if pattern in line:
            return pattern

    return None


def scan_file(path: Path) -> list[Failure]:
    if not path.exists() or is_allowed_path(path):
        return []

    text = path.read_text(encoding="utf-8", errors="ignore")
    if "<auto-generated" in text[:2000]:
        return []

    lines = text.splitlines()
    failures: list[Failure] = []

    allowed_stack: list[bool] = []

    for index, line in enumerate(lines, start=1):
        if_match = PREPROCESSOR_IF_RE.match(line)
        if if_match:
            expression = if_match.group(2)
            allowed_stack.append(expression_mentions_allowed_symbol(expression))
            continue

        if PREPROCESSOR_ELSE_RE.match(line):
            if allowed_stack:
                allowed_stack[-1] = False
            continue

        if PREPROCESSOR_ENDIF_RE.match(line):
            if allowed_stack:
                allowed_stack.pop()
            continue

        pattern = line_has_banned_log(line)
        if pattern is None:
            continue

        inside_allowed_debug_block = any(allowed_stack)

        if inside_allowed_debug_block:
            continue

        failures.append(
            Failure(
                path=path,
                line=index,
                pattern=pattern,
                source_line=line.strip(),
            )
        )

    return failures


def write_markdown_report(
    report_paths: HookReportPaths,
    started: dt.datetime,
    finished: dt.datetime,
    mode: str,
    checked_files: list[Path],
    failures: list[Failure],
) -> None:
    result = "FAIL" if failures else "PASS"
    failed_paths = {failure.path for failure in failures}
    passed_files = [path for path in checked_files if path not in failed_paths]

    lines: list[str] = []

    lines.append(f"# Pre-commit Hook Report: {HOOK_ID}")
    lines.append("")
    lines.append(f"- Hook: `{HOOK_ID}`")
    lines.append(f"- Script: `{SCRIPT_PATH}`")
    lines.append(f"- Mode: `{mode}`")
    lines.append(f"- Started: `{started.isoformat()}`")
    lines.append(f"- Finished: `{finished.isoformat()}`")
    lines.append(f"- Result: `{result}`")
    lines.append(f"- Checked files: `{len(checked_files)}`")
    lines.append(f"- Passed files: `{len(passed_files)}`")
    lines.append(f"- Failed files: `{len(failed_paths)}`")
    lines.append(f"- Failures: `{len(failures)}`")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---:|")
    lines.append(f"| Checked files | {len(checked_files)} |")
    lines.append(f"| Passed files | {len(passed_files)} |")
    lines.append(f"| Failed files | {len(failed_paths)} |")
    lines.append(f"| Failures | {len(failures)} |")
    lines.append(f"| Result | {result} |")
    lines.append("")

    if failures:
        lines.append("## Failures")
        lines.append("")

        for index, failure in enumerate(failures, start=1):
            lines.append(f"### {index}. `{normalize_path(failure.path)}`")
            lines.append("")
            lines.append(f"- Line: `{failure.line}`")
            lines.append(f"- Pattern: `{failure.pattern}`")
            lines.append("- Rule: direct `UnityEngine.Debug.*` / `Debug.*` logging is not allowed in project code unless wrapped by an allowed project debug symbol.")
            lines.append("")
            lines.append("Source line:")
            lines.append("")
            lines.append("```csharp")
            lines.append(failure.source_line)
            lines.append("```")
            lines.append("")
            lines.append("Suggested fixes:")
            lines.append("")
            lines.append("```csharp")
            lines.append("// Preferred runtime path:")
            lines.append("logger.Info(\"...\");")
            lines.append("")
            lines.append("// Temporary debug/evidence path:")
            lines.append("#if GR_COMBAT_DEBUG")
            lines.append("UnityEngine.Debug.Log(\"...\");")
            lines.append("#endif")
            lines.append("```")
            lines.append("")
    else:
        lines.append("## Checked Files")
        lines.append("")
        for file_path in checked_files:
            lines.append(f"- `{normalize_path(file_path)}`")
        lines.append("")

    lines.append("## Allowed Debug Symbols")
    lines.append("")
    for symbol in sorted(ALLOWED_DEBUG_SYMBOLS):
        lines.append(f"- `{symbol}`")
    lines.append("")
    lines.append("## Policy")
    lines.append("")
    lines.append("- Runtime/project code should use `NhemLogger` / `NhemLogging`.")
    lines.append("- Temporary debug logs must be wrapped in a project-prefixed define symbol.")
    lines.append("- Broad symbols such as `DEBUG`, `TEST`, `UNITY_EDITOR`, or `DEVELOPMENT_BUILD` are not allowed by this hook.")
    lines.append("- Vendor/package/plugin folders are intentionally outside this hook's scan roots.")
    lines.append("")

    content = "\n".join(lines) + "\n"
    write_report_to_paths(report_paths, content)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--staged", action="store_true")
    parser.add_argument("--log-file", default=None)

    args = parser.parse_args()
    started = dt.datetime.now()

    if args.all and args.staged:
        print("[FAIL] Use only one mode: --all or --staged.")
        return 1

    if args.staged:
        mode = "staged"
        checked_files = collect_staged_project_cs_files()
    else:
        mode = "all"
        checked_files = collect_all_project_cs_files()

    failures: list[Failure] = []

    for file_path in checked_files:
        failures.extend(scan_file(file_path))

    finished = dt.datetime.now()
    report_paths = build_report_paths(HOOK_ID, args.log_file)

    write_markdown_report(
        report_paths=report_paths,
        started=started,
        finished=finished,
        mode=mode,
        checked_files=checked_files,
        failures=failures,
    )

    print(f"[INFO] Hook report: {report_paths.dated_report}")
    print(f"[INFO] Date latest report: {report_paths.dated_latest}")
    print(f"[INFO] Global latest report: {report_paths.global_latest}")
    print(f"[INFO] Checked files: {len(checked_files)}")

    for failure in failures:
        print(
            f"[FAIL] {normalize_path(failure.path)}:{failure.line}: "
            f"direct Unity debug logging found: {failure.pattern}"
        )

    if failures:
        print()
        print("Use NhemLogger/NhemLogging, or wrap temporary debug logs with an allowed project debug symbol.")
        return 1

    print("[PASS] No direct Unity debug logging found.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
